---
name: SlapperCooldown
author: ReinfyTeam
version: 1.0.2
main: ReinfyTeam\SlapperCooldown\Main
src-namespace-prefix: ReinfyTeam\SlapperCooldown
api: 5.0.0
depend: Slapper
description: Slap the Slapper with Cooldown!
...
