# SlapperCooldownV2
# Updated to PocketMine-MP 4.0.0 Plugin!

# Slapper hit delay in seconds
delay: 0.5
# Message to be displayed as a tip when a player attempts to hit a Slapper too quickly
message: "§cYou're hitting a Slapper too fast!"



# Config Version
# Dont change this unless you know what are you doing!
config-version: "1.0.1"
