<?php

namespace xqwtxon\SlapperCooldownV2;

interface SlapperCooldownInfo {
    /**
     * NOTE FOR DEVELOPERS:
     * CHANGING THIS COULD BREAK THIS PLUGIN!
     * 
     * SUBMITTING PULL REQUEST TO CHANGE THIS PLUGIN COMPATIBLE VERSION WILL AUTOMATICALLY CLOSED!
     * YOU ARE WASTING TIME FOR MODIFYING THIS!
     * 
     * THIS FILE WAS AUTO-GENERATED BY PLUGIN!
    **/
    const PLUGIN_NAME = "SlapperCooldownV2";
    const BRANCH = "main";
    const PLUGIN_DESCRIPTION = "Slap the Slapper with Cooldown!";
    const MAIN = "Main";
    const CONFIG_VERSION = "1.0.0";
    const POCKETMINE_VERSION = "4.2.6";
    const PROTOCOL_VERSION = 486;
    const PLUGIN_VERSION = "2.0.0";
    const VERSION = "v2.0.0";
    const DEFAULT_HIT_DELAY = 0.5;
    const DEFAULT_MESSAGE = "§cYou're hitting a Slapper too fast!";
    const IS_DEVELOPMENT_BUILD = false;
}